spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librarySys?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: library_user
    password: library_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # auto create/update tables
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
